name: Test Code

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-2016]
        # node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest]
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build and test
        run: |
          yarn --ignore-engines
          yarn build
          # yarn test
          npx jest test/dev/dev.test.ts
        env:
          CI: true
      # - name: ssh into server for debugging
      #   uses: mxschmitt/action-tmate@v3
